[context.production]
  command = "yarn build"
  publish = "build/"
  [context.production.environment]
    NODE_VERSION = "14.18.1"

[context.kovan]
  command = "yarn build"
  publish = "build/"
  [context.kovan.environment]
    NODE_VERSION = "14.18.1"
    REACT_APP_CHAIN_ID="42"
    REACT_APP_CLOUD_FUNCTIONS_URL="https://us-central1-kovan-sekerdao.cloudfunctions.net"
    REACT_APP_FIREBASE_API_KEY="AIzaSyBXDL4pBqjo--K5YwlTHZKob_DayMpLIWY"
    REACT_APP_FIREBASE_AUTH_DOMAIN="kovan-sekerdao.firebaseapp.com"
    REACT_APP_FIREBASE_PROJECT_ID="kovan-sekerdao"
    REACT_APP_FIREBASE_STORAGE_BUCKET="kovan-sekerdao.appspot.com"
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID="184142954621"
    REACT_APP_FIREBASE_APP_ID="1:184142954621:web:154e1b0323376b19d07114"
    REACT_APP_GNOSIS_SAFE_PROXY_FACTORY_ADDRESS="0x64F9F99BBdC5Ef6CEEf5Acd9bAd7ea582589A00d"
    REACT_APP_GNOSIS_SAFE_SINGLETON_ADDRESS="0xE51abdf814f8854941b9Fe8e3A4F65CAB4e7A4a8"
    REACT_APP_USUL_MASTERCOPY_ADDRESS="0x5BAC25BF575Cec88EAC9e95938Cd1F9D9D11F098"
    REACT_APP_OZ_LINEAR_MASTER_ADDRESS="0x66E3493d36FF942b2D6897d53C2d46435862e527"
    REACT_APP_MULTI_SEND_ADDRESS="0xfe933df9FDD13b8f52D97ad4b1C2fBBB81be5CC9"
    REACT_APP_MODULE_FACTORY_ADDRESS="0x85f56447c8b90214aC69d457b5E2B937f73793aE"
    # TODO
    #REACT_APP_DOMAIN_ADDRESS=
    #REACT_APP_WETH_ADDRESS=
    #REACT_APP_PROXY_ADDRESS=
    #REACT_APP_AUCTION_ADDRESS=
