[context.production]
  command = "yarn build"
  publish = "build/"
  [context.production.environment]
    NODE_VERSION = "14.18.1"

[context.rinkeby]
  command = "yarn build"
  publish = "build/"
  [context.rinkeby.environment]
    NODE_VERSION = "14.18.1"
    REACT_APP_CHAIN_ID="4"
    REACT_APP_CLOUD_FUNCTIONS_URL="https://us-central1-token-walk.cloudfunctions.net"
    REACT_APP_FIREBASE_API_KEY="AIzaSyBiHQdFu-X9eib9VKzbtj_N0XAmHhklR_4"
    REACT_APP_FIREBASE_AUTH_DOMAIN="token-walk.firebaseapp.com"
    REACT_APP_FIREBASE_PROJECT_ID="token-walk"
    REACT_APP_FIREBASE_STORAGE_BUCKET="token-walk.appspot.com"
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID="761590584693"
    REACT_APP_FIREBASE_APP_ID="1:761590584693:web:bb79592e4d2e103fc2ef3c"
    REACT_APP_GNOSIS_SAFE_PROXY_FACTORY_ADDRESS="0xE89ce3bcD35bA068A9F9d906896D3d03Ad5C30EC"
    REACT_APP_USUL_MASTERCOPY_ADDRESS="0x0bcE608Dce5B99aA7Cd89de09447A33b347aa294"
    REACT_APP_OZ_LINEAR_MASTER_ADDRESS="0xc0F14564aA2c295333e45bB33788F43A8A84739c"
    REACT_APP_MULTI_SEND_ADDRESS="0x2890dd2Cf1E4881b630bd680E50439b9DE00AC02"
    REACT_APP_MODULE_FACTORY_ADDRESS="0xb113d1D1bB1bF3B51418B1de9D29b1aaA7Df1007"
    REACT_APP_DOMAIN_ADDRESS="0xa5676205dBd9ffa11038eB4661f785942E7701D5"
    REACT_APP_AUCTION_ADDRESS="0x3D8568Dd1077eb3d3D6A4dB31Fe3a76183C2bCC5"
